jobs:
  # - name: deploy-ecs-basic_runCI
  #   type: runCI
  #   flags:
  #     - deploy-ecs-basic
  #   steps:
  #     - OUT: deploy-ecs-basic-image

  - name: deploy-ecs-basic-manifest
    type: manifest
    flags:
      - deploy-ecs-basic
    steps:
     - IN: deploy-ecs-basic-image
     - TASK: managed

  - name: deploy-ecs-basic-deploy
    type: deploy
    flags:
      - deploy-ecs-basic
    steps:
      - IN: deploy-ecs-basic-manifest
      - IN: deploy-ecs-basic-docker-options
      - IN: deploy-ecs-basic-ecs-cluster
      - TASK: managed
        deployMethod: upgrade
